# import libs

In [616]:
import numpy as np
#better view to data
np.set_printoptions(suppress=True,linewidth=100 , precision= 2)

# import the dataset

In [617]:
loan_data=np.genfromtxt("loan-data.csv",delimiter=';',skip_header= True)
loan_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]],
      shape=(10000, 14))

In [618]:
#check for missing values
np.isnan(loan_data).sum()

np.int64(88005)

In [619]:
#create variables to fill the missing values
temporary_fill= np.nanmax(loan_data)+1
temporary_mean=np.nanmean(loan_data,axis=0)
temporary_mean

C:\Users\abdel\AppData\Local\Temp\ipykernel_39220\3626976304.py:3: RuntimeWarning: Mean of empty slice
  temporary_mean=np.nanmean(loan_data,axis=0)


array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [620]:
temp_stats=np.array([np.nanmin(loan_data,axis=0),
                     np.nanmean(loan_data,axis=0),
                     np.nanmax(loan_data,axis=0)])
temp_stats

C:\Users\abdel\AppData\Local\Temp\ipykernel_39220\3059567367.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stats=np.array([np.nanmin(loan_data,axis=0),
C:\Users\abdel\AppData\Local\Temp\ipykernel_39220\3059567367.py:2: RuntimeWarning: Mean of empty slice
  np.nanmean(loan_data,axis=0),
C:\Users\abdel\AppData\Local\Temp\ipykernel_39220\3059567367.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(loan_data,axis=0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

# Splitting the dataset into numeric and nonumerics arrays 


In [621]:
# create an array for the string columns
# 1 search the index of columns where their mean value is nan 
columns_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()
columns_strings


array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [622]:
# 2 search the numeric columns
columns_numeric = np.argwhere(np.isnan(temporary_mean)==False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13])

In [623]:
# 3 import the no numeric data
loan_data_strings=np.genfromtxt("loan-data.csv",delimiter=';',skip_header= True,autostrip=True,usecols=columns_strings,dtype=str)
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      shape=(10000, 8), dtype='<U69')

In [624]:
# 4 import the numeric dataset and filling the missing value directly with the max value (for each column  )
loan_data_numeric=np.genfromtxt("loan-data.csv",delimiter=';',skip_header= True,autostrip=True,usecols=columns_numeric,filling_values=temporary_fill)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]],
      shape=(10000, 6))

In [625]:
# extract the dataset headers 
headers=np.genfromtxt("loan-data.csv",delimiter=';',skip_footer=loan_data.shape[0],dtype=str)
headers
# crate header for each numeric and strings datasets
numeric_headers,strings_headers=headers[columns_numeric],headers[columns_strings]
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# create checkpoints

In [626]:
def checkpoint(file_name,checkpoint_header,checkpoint_data):
    np.savez(file_name,header=checkpoint_header,data=checkpoint_data)
    checkpoint_variable=np.load(file_name +".npz")
    return(checkpoint_variable)

In [627]:
#save the string dataset into a checkpoint
checkpoint_test=checkpoint("checkpoint_test",strings_headers,loan_data_strings)
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      shape=(10000, 8), dtype='<U69')

In [628]:
#save the string dataset into a checkpoint
checkpoint_numeric_data= checkpoint("numeric_dataset",numeric_headers,loan_data_numeric)
checkpoint_numeric_data['data']

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]],
      shape=(10000, 6))

# manupilate the Text dataset

In [629]:
strings_headers

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

## the issue date column

In [630]:
strings_headers[0]="issue_date"

In [631]:
loan_data_strings[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], shape=(10000,), dtype='<U69')

In [632]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [633]:
loan_data_strings[:,0]=np.chararray.strip(loan_data_strings[:,0],"-15")
np.unique(loan_data_strings[:,0])

C:\Users\abdel\AppData\Local\Temp\ipykernel_39220\3031855765.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  loan_data_strings[:,0]=np.chararray.strip(loan_data_strings[:,0],"-15")


array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [634]:
#create a months array 
months=np.array(['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep', 'Oct','Nov','Dec'])
#change the columns value from a month string to month number
for  i in range(13):
    loan_data_strings[:,0]= np.where(loan_data_strings[:,0]==months[i],
                                    str(i),loan_data_strings[:,0])
                                    


In [635]:
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [636]:
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [637]:
# split the values into two different groups (good(value:1),bad(value:0))
bad_status= np.array(['', 'Charged Off', 'Default','Late (31-120 days)'])
loan_data_strings[:,1]=np.where(np.isin(loan_data_strings[:,1],bad_status),0,1)
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

In [638]:
# the column terms
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

## manupilate the column term

In [639]:
loan_data_strings[:,2]=np.chararray.strip(loan_data_strings[:,2]," months")
np.unique(loan_data_strings[:,2])
strings_headers[2]="term_months"
# fill the missing value with the worst value 
loan_data_strings[:,2]=np.where(loan_data_strings[:,2]=='','60',loan_data_strings[:,2])

C:\Users\abdel\AppData\Local\Temp\ipykernel_39220\4207898543.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  loan_data_strings[:,2]=np.chararray.strip(loan_data_strings[:,2]," months")


In [640]:
#check the results
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

In [641]:
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [642]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [643]:
#fill the missing value in the column sub-category
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4]=np.where((loan_data_strings[:,4]=='')&(loan_data_strings[:,3]==i),
                                    i+'5',
                                    loan_data_strings[:,4]
                                    
                                    )

In [644]:
np.unique(loan_data_strings[:,4],return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

In [645]:
loan_data_strings[:,4]=np.where(loan_data_strings[:,4]=='',
                                'H',
                                loan_data_strings[:,4])
np.unique(loan_data_strings[:,4],return_counts=True)

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9]))

In [646]:
loan_data_strings=np.delete(loan_data_strings,3,axis=1)
strings_headers=np.delete(strings_headers,3)

In [647]:
np.unique(loan_data_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H'], dtype='<U69')

In [648]:
strings_headers

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [649]:
#create a dic with the subcategory as key and values as int
Key= list(np.unique(loan_data_strings[:,3]))

value=list(range(1,np.unique(loan_data_strings[:,3]).shape[0]+1))
dic_sub_category= dict(zip(Key,value))
dic_sub_category

{np.str_('A1'): 1,
 np.str_('A2'): 2,
 np.str_('A3'): 3,
 np.str_('A4'): 4,
 np.str_('A5'): 5,
 np.str_('B1'): 6,
 np.str_('B2'): 7,
 np.str_('B3'): 8,
 np.str_('B4'): 9,
 np.str_('B5'): 10,
 np.str_('C1'): 11,
 np.str_('C2'): 12,
 np.str_('C3'): 13,
 np.str_('C4'): 14,
 np.str_('C5'): 15,
 np.str_('D1'): 16,
 np.str_('D2'): 17,
 np.str_('D3'): 18,
 np.str_('D4'): 19,
 np.str_('D5'): 20,
 np.str_('E1'): 21,
 np.str_('E2'): 22,
 np.str_('E3'): 23,
 np.str_('E4'): 24,
 np.str_('E5'): 25,
 np.str_('F1'): 26,
 np.str_('F2'): 27,
 np.str_('F3'): 28,
 np.str_('F4'): 29,
 np.str_('F5'): 30,
 np.str_('G1'): 31,
 np.str_('G2'): 32,
 np.str_('G3'): 33,
 np.str_('G4'): 34,
 np.str_('G5'): 35,
 np.str_('H'): 36}

In [650]:
for i in np.unique(loan_data_strings[:,3]):
    loan_data_strings[:,3]=np.where(loan_data_strings[:,3]==i,
                                    str(dic_sub_category[i]),
                                    loan_data_strings[:,3])
                                    

In [651]:
loan_data_strings[:,3]

array(['13', '5', '10', ..., '5', '17', '4'], shape=(10000,), dtype='<U69')

## column verification status 


In [652]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [653]:
loan_data_strings[:,4] = np.where(((loan_data_strings[:,4]== '')| (loan_data_strings[:,4]=='Not Verified')),str(0),str(1))

In [654]:
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

# url column 

In [655]:
np.unique(loan_data_strings[:,5])

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994'],
      shape=(10000,), dtype='<U69')

In [656]:
np.chararray.strip(loan_data_strings[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

C:\Users\abdel\AppData\Local\Temp\ipykernel_39220\636810945.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  np.chararray.strip(loan_data_strings[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')


array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
      shape=(10000,), dtype='<U69')

In [657]:
#the numbers in the url column are the same in the id column. so we can delete the url column
loan_data_strings=np.delete(loan_data_strings,5,axis=1)
strings_headers = np.delete(strings_headers,5)

In [658]:
#checking result
strings_headers
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], shape=(10000,), dtype='<U69')

## column adress state

In [659]:
state_names,state_counts=np.unique(loan_data_strings[:,5],return_counts=True)
state_counts_ordered= np.argsort(-state_counts)
state_names[state_counts_ordered],state_counts[state_counts_ordered]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'TN', 'CT', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DC', 'DE', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10]))

In [660]:
# deal with missing value 
loan_data_strings[:,5]=np.where(loan_data_strings[:,5]=='',str(0),loan_data_strings[:,5])

In [661]:
# devide the state into 4  region groups
west_state= np.array(['WA','OR','CA','NV','ID','MT','WY','UT','CO','AZ','NM','HI','AK'])
south_state=np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
midwest_state=np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
east_state= np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [662]:
#assign a number to each state according to its region
loan_data_strings[:,5]=np.where((np.isin(loan_data_strings[:,5],west_state)),str(1),loan_data_strings[:,5])
loan_data_strings[:,5]=np.where((np.isin(loan_data_strings[:,5],south_state)),str(2),loan_data_strings[:,5])
loan_data_strings[:,5]=np.where((np.isin(loan_data_strings[:,5],midwest_state)),str(3),loan_data_strings[:,5])
loan_data_strings[:,5]=np.where((np.isin(loan_data_strings[:,5],east_state)),str(4),loan_data_strings[:,5])


In [663]:
#check for results
np.unique(loan_data_strings[:,5],return_counts=True)

(array(['0', '1', '2', '3', '4'], dtype='<U69'),
 array([ 500, 2467, 3384, 1733, 1916]))

## make checkpoint

In [664]:
loan_data_strings=loan_data_strings.astype(int)
string_checkpoint=checkpoint('stringdata_transformed',strings_headers,loan_data_strings)
string_data_transformed['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], shape=(10000, 6))

# manipulating numeric columns

In [665]:
np.isnan(loan_data_numeric)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]], shape=(10000, 6))

In [666]:
temporary_fill

np.float64(68616520.0)

In [667]:
np.isin(loan_data_numeric[:,0],temporary_fill).sum()

np.int64(0)

In [668]:
temp_stats[:,columns_numeric]
# in this stats firsrt row : min values  ,second row:mean(),third row :max()

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [669]:
temp_stats[0,columns_numeric[2]]

np.float64(1000.0)

In [670]:
#check for the column funded_amnt if there is missingfilled filled with the temporary_fill varibale(max)
np.isin(loan_data_numeric[:,2],temporary_fill).sum()
#result: 500 we will change the value to the min assuming the worst case of the risk 
#
loan_data_numeric[:,2]=np.where(loan_data_numeric[:,2]==temporary_fill,
                                temp_stats[0,columns_numeric[2]],loan_data_numeric[:,2])

In [671]:
np.isin(loan_data_numeric[:,2],temp_stats[0]).sum()
#result the 500 value are replaced with the min values

np.int64(528)

## columns laoned amount ,interest rate,total payment,installment

In [672]:
columns_numeric

array([ 0,  2,  4,  6,  7, 13])

In [673]:
#for this columns we will replace the filled values with the max value .
#[1,3,4,5] indexes for the columns in the columns_numeric
for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i]==temporary_fill,
                                      temp_stats[2,columns_numeric[i]],
                                      loan_data_numeric[:,i])


In [674]:
np.isin(loan_data_numeric[:,5],temp_stats[2]).sum()

np.int64(501)

In [675]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]],
      shape=(10000, 6))

# Currency change

In [676]:
#we will use the Close column in our data (index =3)
EURO_USD= np.genfromtxt("EUR-USD.csv",autostrip= True,delimiter= ',',usecols=3)
#delete nan value
EURO_USD=np.delete(EURO_USD,0)
EURO_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [677]:
np.unique(loan_data_strings[:,0])


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [678]:
exchange_rate=loan_data_strings[:,0]
for i in range(1,13):
    exchange_rate=np.where(exchange_rate==i,
                           EURO_USD[i-1],
                           exchange_rate)
#for the 0 value we put the mean
exchange_rate=np.where(exchange_rate==0,
                       np.mean(EURO_USD),
                       exchange_rate)
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09], shape=(10000,))

In [679]:
exchange_rate= np.reshape(exchange_rate,(10000,1))
exchange_rate.shape

(10000, 1)

In [680]:
loan_data_numeric.shape

(10000, 6)

In [681]:
#add the exchange rate column to the numeric table 
loan_data_numeric=np.hstack((loan_data_numeric,exchange_rate))
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]],
      shape=(10000, 7))

In [682]:
#add the column header to the headers array
numeric_headers= np.concatenate((numeric_headers,np.array(['exchange_rate'])))

In [683]:
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [684]:
dollar_columns=np.array([1,2,4,5])
loan_data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09], shape=(10000,))

In [685]:
# add 4 new columns for every column after the eschange from us to euro

for i in dollar_columns:
    loan_data_numeric=np.hstack((loan_data_numeric,np.reshape(loan_data_numeric[:,i]/loan_data_numeric[:,6],(10000,1))))

In [686]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]],
      shape=(10000, 11))

In [687]:
new_headers=np.array([col_name + '_EUR' for col_name in numeric_headers[dollar_columns]])
new_headers

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [688]:
numeric_headers=np.concatenate((numeric_headers,new_headers))
numeric_headers

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [689]:
numeric_headers[dollar_columns]=np.array([col_name+'_USD' for col_name in numeric_headers[dollar_columns]])
numeric_headers

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [690]:
#rearrange the columns 
column_index_order= [0,1,7,2,8,3,4,9,5,10,6]
numeric_headers=numeric_headers[column_index_order]
numeric_headers

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [691]:
loan_data_numeric=loan_data_numeric[:,column_index_order]

## interest column :interest rate chnage the values to one between 0 and 1 

In [692]:
loan_data_numeric[:,5]=loan_data_numeric[:,5]/100

In [693]:
loan_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29], shape=(10000,))

In [694]:
numeric_checkpoint= checkpoint("final_data",numeric_headers,loan_data_numeric)

In [696]:
final_dataset_numeric['header'],final_dataset_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]],
       shape=(10000, 11)))

# the final complete dataset

In [699]:
string_checkpoint['data'].shape

(10000, 6)

In [700]:
numeric_checkpoint['data'].shape

(10000, 11)

In [709]:
loan_data=np.hstack((numeric_checkpoint['data'],string_checkpoint['data']))

In [703]:
np.isnan(loan_data).sum()

np.int64(0)

In [705]:
final_headers=np.concatenate((numeric_checkpoint['header'],string_checkpoint['header']))

In [713]:
loan_data=loan_data[np.argsort(loan_data[:,0])]

In [715]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], shape=(10000,))

In [716]:
final_data=np.vstack((final_headers,loan_data))

In [717]:
final_data

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'addr_state'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']],
      shape=(10001, 17), dtype='<U32')

# export the final dataset into a new file

In [718]:
np.savetxt("loan-data-preprocessed.csv",final_data,delimiter=',',fmt="%s")